[project]
name = "football-predict"
version = "0.0.4"
description = "Machine learning model for predicting football outcomes"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "polars>=1.34.0",
    "pyarrow>=21.0.0",
    "scraperfc>=3.4.0",
    "soccerdata>=1.8.2",
]
